"""Initial

Revision ID: 3191d789ad3a
Revises: 
Create Date: 2023-06-25 14:55:59.053996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191d789ad3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business direction', sa.String(), nullable=False),
    sa.Column('bot development platform', sa.String(), nullable=False),
    sa.Column('min_budget', sa.Integer(), nullable=False),
    sa.Column('max_budget', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('permissons', sa.JSON(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('application')
    # ### end Alembic commands ###
